const API='https://api.binance.com';let TF='1h', rows=[], busy=false;
const $=id=>document.getElementById(id); document.querySelectorAll('#tf button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#tf button').forEach(x=>x.classList.remove('active'));b.classList.add('active');TF=b.dataset.tf;scan()});
$('refresh').onclick=scan;$('limit').onchange=scan;$('minVol').onchange=scan;$('search').oninput=render;$('view').onchange=render;
function ema(a,n){let k=2/(n+1),e=a[0];for(let i=1;i<a.length;i++)e=a[i]*k+e*(1-k);return e}
function mean(a){return a.reduce((x,y)=>x+y,0)/a.length}function stdev(a){let m=mean(a);return Math.sqrt(mean(a.map(x=>(x-m)**2)))}
function calc(k){let c=k.map(x=>+x[4]),h=k.map(x=>+x[2]),l=k.map(x=>+x[3]),v=k.map(x=>+x[5]);let p=c.at(-1), e7=ema(c,7),e25=ema(c,25),e99=ema(c,99), n=20, m=mean(c.slice(-n)),sd=stdev(c.slice(-n)), bw=(4*sd)/m*100, hi=Math.max(...h.slice(-50)),lo=Math.min(...l.slice(-50));let vr=mean(v.slice(-5))/mean(v.slice(-30));let tr=[],atr=0,plus=0,minus=0;for(let i=1;i<c.length;i++){let up=h[i]-h[i-1],dn=l[i-1]-l[i];tr.push(Math.max(h[i]-l[i],Math.abs(h[i]-c[i-1]),Math.abs(l[i]-c[i-1])));plus+=up>dn&&up>0?up:0;minus+=dn>up&&dn>0?dn:0}atr=mean(tr.slice(-14));let adx=100*Math.abs(plus-minus)/(plus+minus||1);let range=Math.max(hi-lo,p*.0001);let side=clamp(100-(bw*7)-Math.min(35,adx*.45)+Math.max(0,20-vr*8),0,100);let dist=Math.max(0,(hi-p)/range);let pre=clamp(side*.45+(1-Math.min(1,dist))*35+Math.min(20,Math.max(0,vr-1)*18)+(e7>e25?5:0),0,100);let br=clamp((p>hi*0.995?45:0)+(vr>=1.5?25:vr>=1.2?12:0)+(e7>e25?15:0)+(adx>25?15:0),0,100);let radar=Math.round(side*.4+pre*.35+br*.25);return{p,e7,e25,e99,bw,vr,adx,side,pre,br,radar,support:lo,resistance:hi}}
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
async function get(url){let r=await fetch(url);if(!r.ok)throw Error(r.status);return r.json()}
async function scan(){if(busy)return;busy=true;$('status').textContent='Đang lấy Top coin...';rows=[];render();try{let info=await get(API+'/api/v3/exchangeInfo');let symbols=new Set(info.symbols.filter(s=>s.status==='TRADING'&&s.quoteAsset==='USDT'&&s.isSpotTradingAllowed&&!/UP|DOWN|BULL|BEAR/.test(s.baseAsset)).map(s=>s.symbol));let tick=await get(API+'/api/v3/ticker/24hr');let min=+$('minVol').value, lim=+$('limit').value;let top=tick.filter(x=>symbols.has(x.symbol)&&+x.quoteVolume>=min).sort((a,b)=>+b.quoteVolume-+a.quoteVolume).slice(0,lim);$('status').textContent=`Đang quét ${top.length} coin • ${TF}`;let out=[],done=0;for(let i=0;i<top.length;i+=8){let batch=top.slice(i,i+8);let got=await Promise.allSettled(batch.map(async t=>{let k=await get(`${API}/api/v3/klines?symbol=${t.symbol}&interval=${TF}&limit=120`);if(k.length<60)throw 0;return {...t,m:calc(k)}}));got.forEach((g,j)=>{if(g.status==='fulfilled')out.push(g.value)});done+=batch.length;$('status').textContent=`Đã quét ${Math.min(done,top.length)}/${top.length}`;rows=out.sort((a,b)=>b.m.radar-a.m.radar);render()}$('status').textContent=`Hoàn tất • ${rows.length} coin`;localStorage.setItem('sideway_v22',JSON.stringify({tf:TF,rows,time:Date.now()}))}catch(e){$('status').textContent='Lỗi kết nối Binance: '+e.message}busy=false}
function render(){let q=$('search').value.toUpperCase(),v=$('view').value;let a=rows.filter(x=>x.symbol.includes(q)).filter(x=>v==='all'||v==='opportunity'?(x.m.side>=75&&x.m.pre>=75&&x.m.br<80):v==='accum'?x.m.side>=75:v==='pre'?x.m.pre>=75&&x.m.br<80:v==='breakout'?x.m.br>=80:v==='radar'?true:true);if(v==='radar')a=a.sort((x,y)=>y.m.radar-x.m.radar).slice(0,30);$('count').textContent=a.length+' coin';$('cards').innerHTML=a.length?a.map(x=>card(x)).join(''):'<div class="empty">Chưa có coin phù hợp bộ lọc.</div>'}
function card(x){let m=x.m;let cls=m.br>=80?'hot':m.side>=75?'good':'';return `<article class="card ${cls}"><div class="top"><div><div class="sym">${x.symbol}</div><div class="price">${fmt(m.p)} USDT • Vol 24H ${fmtVol(+x.quoteVolume)}</div></div><b>RADAR ${m.radar}</b></div><div class="badges"><span class="badge">SIDE ${m.side.toFixed(0)}</span><span class="badge">PRE ${m.pre.toFixed(0)}</span><span class="badge">BREAK ${m.br.toFixed(0)}</span></div><div class="grid"><div class="metric"><b>${m.adx.toFixed(1)}</b><small>ADX</small></div><div class="metric"><b>${m.bw.toFixed(2)}%</b><small>BB Width</small></div><div class="metric"><b>${m.vr.toFixed(2)}x</b><small>Volume Ratio</small></div><div class="metric"><b>${fmt(m.e25)}</b><small>EMA25</small></div></div><div class="levels"><span>🟢 Hỗ trợ ${fmt(m.support)}</span><span>🔴 Cản ${fmt(m.resistance)}</span></div></article>`}
function fmt(n){if(!isFinite(n))return'-';return n>=100? n.toFixed(2):n>=1?n.toFixed(4):n.toPrecision(5)}function fmtVol(n){return n>=1e9?(n/1e9).toFixed(1)+'B':n>=1e6?(n/1e6).toFixed(1)+'M':(n/1e3).toFixed(0)+'K'}
try{let c=JSON.parse(localStorage.getItem('sideway_v22'));if(c&&c.rows){rows=c.rows;render()}}catch{}scan();
